workspace:
  base: /drone
  path: src/github.com/owncloud-docker/client

branches:
  - build

clone:
  git:
    image: plugins/git
    pull: true
    tags: true

pipeline:
  docker:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloud/client
    tags:
      - build
    dry_run: true
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloud/client
    tags:
      - build
    when:
      event: [ push ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_urls ]
    when:
      local: false
      event: [ push ]

  downstream:
    image: plugins/downstream:1
    pull: true
    secrets: [ drone_token ]
    server: https://drone.owncloud.com
    last_successful: true
    repositories:
      - owncloud-docker/smashbox@build
    when:
      local: false
      event: [ push ]
      status: [ success ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]
